defaultName: Traveler

server:
  rootPath: /api/

  applicationConnectors:
      - type: http
        port: 8080
      - type: https
        port: 8443
        keyStorePath: example.keystore
        keyStorePassword: example

  adminConnectors:
    - type: http
      port: 8081
    - type: https
      port: 8444
      keyStorePath: example.keystore
      keyStorePassword: example

swagger:
  resourcePackage: fi.istrange.traveler.resources
  title: travel.er API

jwtCookieAuth:
  secretSeed: null
  secure: true
  httpOnly: false
  sessionExpiryVolatile: PT30m
  sessionExpiryPersistent: P7d

database:
  driverClass: org.postgresql.Driver
  user: ${(env.DB_USER)!"test"}
  password: ${(env.DB_PASSWORD)!"test"}
  url: jdbc:postgresql://${(env.DB_HOST)!"127.0.0.1"}:${(env.DB_PORT)!"5432"}/${(env.DB_NAME)!"traveler_test"}

jooq:
  # The flavor of SQL to generate. If not specified, it will be inferred from the JDBC connection URL.  (default: null)
  dialect: POSTGRES
  # Whether to write generated SQL to a logger before execution.  (default: no)
  logExecutedSql: yes
  # Whether to include schema names in generated SQL.  (default: yes)
  renderSchema: yes
  # How names should be rendered in generated SQL.  One of QUOTED, AS_IS, LOWER, or UPPER.  (default: QUOTED)
  renderNameStyle: QUOTED
  # How keywords should be rendered in generated SQL.  One of LOWER, UPPER.  (default: UPPER)
  renderKeywordStyle: LOWER
  # Whether generated SQL should be pretty-printed.  (default: no)
  renderFormatted: no
  # How parameters should be represented.  One of INDEXED, NAMED, or INLINE.  (default: INDEXED)
  paramType: INDEXED
  # How statements should be generated; one of PREPARED_STATEMENT or STATIC_STATEMENT.  (default: PREPARED_STATEMENT)
  statementType: PREPARED_STATEMENT
  # Whether internal jOOQ logging should be enabled.  (default: no)
  executeLogging: no
  # Whether optimistic locking should be enabled.  (default: no)
  executeWithOptimisticLocking: no
  # Whether returned records should be 'attached' to the jOOQ context.  (default: yes)
  attachRecords: yes
  # Whether primary-key fields should be updatable.  (default: no)
  updatablePrimaryKeys: no