/*
 * This file is generated by jOOQ.
*/
package fi.istrange.traveler.db.tables.daos;


import fi.istrange.traveler.db.tables.ChatRoom;
import fi.istrange.traveler.db.tables.records.ChatRoomRecord;

import java.sql.Date;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChatRoomDao extends DAOImpl<ChatRoomRecord, fi.istrange.traveler.db.tables.pojos.ChatRoom, Long> {

    /**
     * Create a new ChatRoomDao without any configuration
     */
    public ChatRoomDao() {
        super(ChatRoom.CHAT_ROOM, fi.istrange.traveler.db.tables.pojos.ChatRoom.class);
    }

    /**
     * Create a new ChatRoomDao with an attached configuration
     */
    public ChatRoomDao(Configuration configuration) {
        super(ChatRoom.CHAT_ROOM, fi.istrange.traveler.db.tables.pojos.ChatRoom.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(fi.istrange.traveler.db.tables.pojos.ChatRoom object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<fi.istrange.traveler.db.tables.pojos.ChatRoom> fetchById(Long... values) {
        return fetch(ChatRoom.CHAT_ROOM.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public fi.istrange.traveler.db.tables.pojos.ChatRoom fetchOneById(Long value) {
        return fetchOne(ChatRoom.CHAT_ROOM.ID, value);
    }

    /**
     * Fetch records that have <code>active IN (values)</code>
     */
    public List<fi.istrange.traveler.db.tables.pojos.ChatRoom> fetchByActive(Boolean... values) {
        return fetch(ChatRoom.CHAT_ROOM.ACTIVE, values);
    }

    /**
     * Fetch records that have <code>creation_time IN (values)</code>
     */
    public List<fi.istrange.traveler.db.tables.pojos.ChatRoom> fetchByCreationTime(Date... values) {
        return fetch(ChatRoom.CHAT_ROOM.CREATION_TIME, values);
    }
}
