/*
 * This file is generated by jOOQ.
*/
package fi.istrange.traveler.db.tables.daos;


import fi.istrange.traveler.db.tables.Message;
import fi.istrange.traveler.db.tables.records.MessageRecord;

import java.sql.Date;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MessageDao extends DAOImpl<MessageRecord, fi.istrange.traveler.db.tables.pojos.Message, Long> {

    /**
     * Create a new MessageDao without any configuration
     */
    public MessageDao() {
        super(Message.MESSAGE, fi.istrange.traveler.db.tables.pojos.Message.class);
    }

    /**
     * Create a new MessageDao with an attached configuration
     */
    public MessageDao(Configuration configuration) {
        super(Message.MESSAGE, fi.istrange.traveler.db.tables.pojos.Message.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(fi.istrange.traveler.db.tables.pojos.Message object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<fi.istrange.traveler.db.tables.pojos.Message> fetchById(Long... values) {
        return fetch(Message.MESSAGE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public fi.istrange.traveler.db.tables.pojos.Message fetchOneById(Long value) {
        return fetchOne(Message.MESSAGE.ID, value);
    }

    /**
     * Fetch records that have <code>message_text IN (values)</code>
     */
    public List<fi.istrange.traveler.db.tables.pojos.Message> fetchByMessageText(String... values) {
        return fetch(Message.MESSAGE.MESSAGE_TEXT, values);
    }

    /**
     * Fetch records that have <code>creation_time IN (values)</code>
     */
    public List<fi.istrange.traveler.db.tables.pojos.Message> fetchByCreationTime(Date... values) {
        return fetch(Message.MESSAGE.CREATION_TIME, values);
    }

    /**
     * Fetch records that have <code>username IN (values)</code>
     */
    public List<fi.istrange.traveler.db.tables.pojos.Message> fetchByUsername(String... values) {
        return fetch(Message.MESSAGE.USERNAME, values);
    }

    /**
     * Fetch records that have <code>chat_room_id IN (values)</code>
     */
    public List<fi.istrange.traveler.db.tables.pojos.Message> fetchByChatRoomId(Long... values) {
        return fetch(Message.MESSAGE.CHAT_ROOM_ID, values);
    }
}
