/*
 * This file is generated by jOOQ.
*/
package fi.istrange.traveler.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChatRoomUser implements Serializable {

    private static final long serialVersionUID = 575520435;

    private Long   chatRoomId;
    private String username;

    public ChatRoomUser() {}

    public ChatRoomUser(ChatRoomUser value) {
        this.chatRoomId = value.chatRoomId;
        this.username = value.username;
    }

    public ChatRoomUser(
        Long   chatRoomId,
        String username
    ) {
        this.chatRoomId = chatRoomId;
        this.username = username;
    }

    public Long getChatRoomId() {
        return this.chatRoomId;
    }

    public void setChatRoomId(Long chatRoomId) {
        this.chatRoomId = chatRoomId;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ChatRoomUser (");

        sb.append(chatRoomId);
        sb.append(", ").append(username);

        sb.append(")");
        return sb.toString();
    }
}
