/*
 * This file is generated by jOOQ.
*/
package fi.istrange.traveler.db.tables.pojos;


import java.io.Serializable;
import java.sql.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChatRoom implements Serializable {

    private static final long serialVersionUID = 1258233722;

    private Long    id;
    private Boolean active;
    private Date    creationTime;

    public ChatRoom() {}

    public ChatRoom(ChatRoom value) {
        this.id = value.id;
        this.active = value.active;
        this.creationTime = value.creationTime;
    }

    public ChatRoom(
        Long    id,
        Boolean active,
        Date    creationTime
    ) {
        this.id = id;
        this.active = active;
        this.creationTime = creationTime;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Boolean getActive() {
        return this.active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    public Date getCreationTime() {
        return this.creationTime;
    }

    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ChatRoom (");

        sb.append(id);
        sb.append(", ").append(active);
        sb.append(", ").append(creationTime);

        sb.append(")");
        return sb.toString();
    }
}
